-- MCO — Complete Database Schema
-- Single script. Run entirely in Supabase SQL Editor to build a fresh environment.
-- Safe to re-run on existing databases: all operations use IF NOT EXISTS / CREATE OR REPLACE.
-- Last updated: 2026-05-18

-- ============================================================
-- HELPER: intent_rank()
-- Must be created first — upsert_lead() depends on it.
-- Enforces the one-way intent promotion ratchet.
-- Order: unknown(0) → no_action(1) → not_interested(2) →
--        referral(3) → already_have_contract(4) → interested(5) → booking(6)
-- ============================================================
CREATE OR REPLACE FUNCTION intent_rank(intent TEXT) RETURNS INT AS $$
BEGIN
  RETURN CASE intent
    WHEN 'unknown'                THEN 0
    WHEN 'no_action'              THEN 1
    WHEN 'not_interested'         THEN 2
    WHEN 'referral'               THEN 3
    WHEN 'already_have_contract'  THEN 4
    WHEN 'interested'             THEN 5
    WHEN 'booking'                THEN 6
    ELSE -1
  END;
END;
$$ LANGUAGE plpgsql IMMUTABLE;


-- ============================================================
-- TABLE: leads
-- One row per lead. Primary key is lead_id (UUID).
-- Any of the five identifiers can be used to resolve a lead.
-- All identifier columns are nullable with partial unique indexes
-- so NULL values are allowed but non-NULL values must be unique.
-- ============================================================
CREATE TABLE IF NOT EXISTS leads (
  lead_id                   UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  lead_email                TEXT,
  full_name                 TEXT,
  company                   TEXT,
  linkedin_urn              TEXT,
  linkedin_profile_url      TEXT,
  linkedin_conversation_urn TEXT,
  phone_e164                TEXT,
  first_channel             TEXT CHECK (first_channel IN ('email','linkedin','voice','sms')),
  first_seen_at             TIMESTAMPTZ,
  last_activity_at          TIMESTAMPTZ,
  last_active_channel       TEXT CHECK (last_active_channel IN ('email','linkedin','voice','sms')),
  monday_item_id            TEXT,
  overall_intent            TEXT DEFAULT 'unknown'
                              CHECK (overall_intent IN (
                                'unknown','no_action','not_interested',
                                'referral','already_have_contract','interested','booking'
                              )),
  overall_intent_updated_at TIMESTAMPTZ,
  aimfox_campaign           TEXT,
  email_sender_inbox        TEXT,
  notes                     TEXT,
  created_at                TIMESTAMPTZ DEFAULT NOW()
);

-- Partial unique indexes: allow NULL, enforce uniqueness when set
CREATE UNIQUE INDEX IF NOT EXISTS idx_leads_email_unique
  ON leads(lead_email) WHERE lead_email IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_leads_linkedin_url_unique
  ON leads(linkedin_profile_url) WHERE linkedin_profile_url IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_leads_linkedin_urn_unique
  ON leads(linkedin_urn) WHERE linkedin_urn IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_leads_phone_unique
  ON leads(phone_e164) WHERE phone_e164 IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_leads_intent        ON leads(overall_intent);
CREATE INDEX IF NOT EXISTS idx_leads_last_activity ON leads(last_activity_at DESC);


-- ============================================================
-- TABLE: conversations
-- One row per message, any channel, any direction.
-- event_id is a UUID v4 generated by the caller — used as dedup key.
-- Duplicate event_id writes are caught by insert_conversation_event() RPC.
-- ============================================================
CREATE TABLE IF NOT EXISTS conversations (
  event_id              UUID PRIMARY KEY,
  lead_id               UUID NOT NULL REFERENCES leads(lead_id) ON UPDATE CASCADE ON DELETE CASCADE,
  lead_email            TEXT,
  timestamp             TIMESTAMPTZ NOT NULL,
  channel               TEXT NOT NULL CHECK (channel IN ('email','linkedin','voice','sms')),
  direction             TEXT NOT NULL CHECK (direction IN ('inbound','outbound')),
  content               TEXT,
  content_type          TEXT CHECK (content_type IN ('message','transcript','summary')),
  sender_name           TEXT,
  intent                TEXT CHECK (intent IN (
                          'unknown','no_action','not_interested',
                          'referral','already_have_contract','interested','booking'
                        )),
  metadata_json         JSONB,
  workflow_execution_id TEXT,
  written_at            TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_conv_lead_id   ON conversations(lead_id);
CREATE INDEX IF NOT EXISTS idx_conv_lead_time ON conversations(lead_id, timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_conv_channel   ON conversations(channel);
CREATE INDEX IF NOT EXISTS idx_conv_intent    ON conversations(intent);


-- ============================================================
-- TABLE: follow_up_queue
-- Queued cross-channel follow-ups. Dispatcher polls every 15 min.
-- outcome is written by Post Call Analysis after a voice call ends.
-- ============================================================
CREATE TABLE IF NOT EXISTS follow_up_queue (
  queue_id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  lead_id           UUID NOT NULL REFERENCES leads(lead_id) ON UPDATE CASCADE ON DELETE CASCADE,
  lead_email        TEXT,
  trigger_channel   TEXT CHECK (trigger_channel IN ('email','linkedin','voice','sms')),
  target_channel    TEXT NOT NULL CHECK (target_channel IN ('email','linkedin','voice','sms')),
  trigger_event_id  UUID REFERENCES conversations(event_id),
  scheduled_for     TIMESTAMPTZ NOT NULL,
  status            TEXT NOT NULL DEFAULT 'pending'
                      CHECK (status IN ('pending','sent','skipped','failed')),
  outcome           TEXT CHECK (outcome IN ('answered','voicemail','no_answer','failed')),
  follow_up_context TEXT,
  sent_at           TIMESTAMPTZ,
  created_at        TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_queue_status_time ON follow_up_queue(status, scheduled_for);
CREATE INDEX IF NOT EXISTS idx_queue_lead_id     ON follow_up_queue(lead_id);


-- ============================================================
-- TABLE: phone_map
-- Maps E.164 phone numbers to leads. Used by Retell/voice to
-- resolve a caller back to a lead record.
-- ============================================================
CREATE TABLE IF NOT EXISTS phone_map (
  phone_e164  TEXT PRIMARY KEY,
  lead_id     UUID REFERENCES leads(lead_id) ON UPDATE CASCADE ON DELETE CASCADE,
  lead_email  TEXT,
  source      TEXT CHECK (source IN ('clay','manual','retell')),
  confidence  TEXT CHECK (confidence IN ('high','medium','low')),
  created_at  TIMESTAMPTZ DEFAULT NOW(),
  notes       TEXT
);

CREATE INDEX IF NOT EXISTS idx_phonemap_lead_id ON phone_map(lead_id);


-- ============================================================
-- ROW LEVEL SECURITY
-- Enabled on all tables. No policies = anon key is blocked.
-- The service_role key (used by n8n) bypasses RLS entirely.
-- ============================================================
ALTER TABLE leads            ENABLE ROW LEVEL SECURITY;
ALTER TABLE conversations    ENABLE ROW LEVEL SECURITY;
ALTER TABLE phone_map        ENABLE ROW LEVEL SECURITY;
ALTER TABLE follow_up_queue  ENABLE ROW LEVEL SECURITY;


-- ============================================================
-- RPC: upsert_lead()
-- Creates or updates a lead record. Accepts any combination of
-- identifiers — resolves existing lead by email OR linkedin_url
-- OR linkedin_urn OR phone. Intent never demotes.
-- Returns lead_id so callers can thread it downstream.
-- ============================================================
CREATE OR REPLACE FUNCTION upsert_lead(
  p_lead_email                TEXT    DEFAULT NULL,
  p_linkedin_profile_url      TEXT    DEFAULT NULL,
  p_linkedin_urn              TEXT    DEFAULT NULL,
  p_phone_e164                TEXT    DEFAULT NULL,
  p_full_name                 TEXT    DEFAULT NULL,
  p_company                   TEXT    DEFAULT NULL,
  p_channel                   TEXT    DEFAULT NULL,
  p_monday_item_id            TEXT    DEFAULT NULL,
  p_new_intent                TEXT    DEFAULT NULL,
  p_aimfox_campaign           TEXT    DEFAULT NULL,
  p_email_sender_inbox        TEXT    DEFAULT NULL,
  p_linkedin_conversation_urn TEXT    DEFAULT NULL
) RETURNS TABLE(
  lead_id        UUID,
  lead_email     TEXT,
  lead_created   BOOLEAN,
  monday_item_id TEXT,
  overall_intent TEXT
) AS $$
DECLARE
  v_lead_id        UUID;
  v_lead_email     TEXT;
  v_created        BOOLEAN := FALSE;
  v_monday_item_id TEXT;
  v_overall_intent TEXT;
BEGIN
  -- Multi-identifier resolution: find oldest matching lead record
  SELECT l.lead_id, l.lead_email
    INTO v_lead_id, v_lead_email
    FROM leads l
    WHERE (p_lead_email           IS NOT NULL AND l.lead_email           = p_lead_email)
       OR (p_linkedin_profile_url IS NOT NULL AND l.linkedin_profile_url = p_linkedin_profile_url)
       OR (p_linkedin_urn         IS NOT NULL AND l.linkedin_urn         = p_linkedin_urn)
       OR (p_phone_e164           IS NOT NULL AND l.phone_e164           = p_phone_e164)
    ORDER BY l.created_at ASC
    LIMIT 1;

  IF v_lead_id IS NULL THEN
    -- New lead
    v_created := TRUE;
    INSERT INTO leads (
      lead_email, full_name, company,
      linkedin_urn, linkedin_profile_url, linkedin_conversation_urn,
      phone_e164, first_channel, first_seen_at,
      last_activity_at, last_active_channel,
      monday_item_id, overall_intent, overall_intent_updated_at,
      aimfox_campaign, email_sender_inbox, created_at
    ) VALUES (
      p_lead_email,
      COALESCE(p_full_name, ''),
      COALESCE(p_company, ''),
      p_linkedin_urn,
      p_linkedin_profile_url,
      p_linkedin_conversation_urn,
      p_phone_e164,
      p_channel,
      NOW(), NOW(), p_channel,
      p_monday_item_id,
      COALESCE(p_new_intent, 'unknown'),
      NOW(),
      p_aimfox_campaign,
      p_email_sender_inbox,
      NOW()
    )
    RETURNING leads.lead_id, leads.lead_email INTO v_lead_id, v_lead_email;

  ELSE
    -- Existing lead: fill in missing identifiers, promote intent
    UPDATE leads SET
      lead_email                = COALESCE(p_lead_email,                leads.lead_email),
      full_name                 = COALESCE(NULLIF(p_full_name, ''),     leads.full_name),
      company                   = COALESCE(NULLIF(p_company, ''),       leads.company),
      linkedin_urn              = COALESCE(p_linkedin_urn,              leads.linkedin_urn),
      linkedin_profile_url      = COALESCE(p_linkedin_profile_url,      leads.linkedin_profile_url),
      linkedin_conversation_urn = COALESCE(p_linkedin_conversation_urn, leads.linkedin_conversation_urn),
      phone_e164                = COALESCE(p_phone_e164,                leads.phone_e164),
      last_activity_at          = NOW(),
      last_active_channel       = COALESCE(p_channel,                   leads.last_active_channel),
      monday_item_id            = COALESCE(p_monday_item_id,            leads.monday_item_id),
      aimfox_campaign           = COALESCE(p_aimfox_campaign,           leads.aimfox_campaign),
      email_sender_inbox        = COALESCE(p_email_sender_inbox,        leads.email_sender_inbox),
      overall_intent            = CASE
        WHEN intent_rank(COALESCE(p_new_intent, 'unknown')) > intent_rank(leads.overall_intent)
        THEN COALESCE(p_new_intent, 'unknown')
        ELSE leads.overall_intent
      END,
      overall_intent_updated_at = CASE
        WHEN intent_rank(COALESCE(p_new_intent, 'unknown')) > intent_rank(leads.overall_intent)
        THEN NOW()
        ELSE leads.overall_intent_updated_at
      END
    WHERE leads.lead_id = v_lead_id
    RETURNING leads.lead_email INTO v_lead_email;
  END IF;

  SELECT l.monday_item_id, l.overall_intent
    INTO v_monday_item_id, v_overall_intent
    FROM leads l WHERE l.lead_id = v_lead_id;

  RETURN QUERY SELECT v_lead_id, v_lead_email, v_created, v_monday_item_id, v_overall_intent;
END;
$$ LANGUAGE plpgsql;


-- ============================================================
-- RPC: insert_conversation_event()
-- Inserts one conversation row. Dedup on event_id — safe to retry.
-- Accepts lead_id (preferred) or lead_email (fallback).
-- ============================================================
CREATE OR REPLACE FUNCTION insert_conversation_event(
  p_event_id              UUID,
  p_lead_id               UUID        DEFAULT NULL,
  p_lead_email            TEXT        DEFAULT NULL,
  p_timestamp             TIMESTAMPTZ DEFAULT NOW(),
  p_channel               TEXT        DEFAULT NULL,
  p_direction             TEXT        DEFAULT NULL,
  p_content               TEXT        DEFAULT NULL,
  p_content_type          TEXT        DEFAULT 'message',
  p_sender_name           TEXT        DEFAULT NULL,
  p_intent                TEXT        DEFAULT 'unknown',
  p_metadata              JSONB       DEFAULT '{}',
  p_workflow_execution_id TEXT        DEFAULT NULL
) RETURNS JSONB AS $$
DECLARE
  v_lead_id    UUID;
  v_lead_email TEXT;
BEGIN
  -- Dedup: silent no-op if event already recorded
  IF EXISTS (SELECT 1 FROM conversations WHERE event_id = p_event_id) THEN
    RETURN jsonb_build_object('was_new', false, 'event_id', p_event_id::text);
  END IF;

  -- Resolve lead
  IF p_lead_id IS NOT NULL THEN
    v_lead_id := p_lead_id;
    SELECT lead_email INTO v_lead_email FROM leads WHERE lead_id = v_lead_id;
  ELSIF p_lead_email IS NOT NULL THEN
    SELECT lead_id, lead_email INTO v_lead_id, v_lead_email
      FROM leads WHERE lead_email = p_lead_email;
  END IF;

  IF v_lead_id IS NULL THEN
    RETURN jsonb_build_object(
      'was_new',  false,
      'error',    'lead_not_found',
      'event_id', p_event_id::text
    );
  END IF;

  INSERT INTO conversations (
    event_id, lead_id, lead_email, timestamp, channel, direction,
    content, content_type, sender_name, intent,
    metadata_json, workflow_execution_id
  ) VALUES (
    p_event_id, v_lead_id, v_lead_email,
    p_timestamp, p_channel, p_direction,
    p_content, p_content_type, p_sender_name, p_intent,
    p_metadata, p_workflow_execution_id
  );

  RETURN jsonb_build_object(
    'was_new',  true,
    'event_id', p_event_id::text,
    'lead_id',  v_lead_id::text
  );
END;
$$ LANGUAGE plpgsql;


-- ============================================================
-- RPC: fetch_lead_context()
-- Returns lead record + last N conversations for any identifier.
-- lead_id is the fastest lookup — pass it whenever available.
-- Read-only. Never writes.
-- ============================================================
CREATE OR REPLACE FUNCTION fetch_lead_context(
  p_lead_id              UUID    DEFAULT NULL,
  p_lead_email           TEXT    DEFAULT NULL,
  p_linkedin_profile_url TEXT    DEFAULT NULL,
  p_phone_e164           TEXT    DEFAULT NULL,
  p_max_events           INT     DEFAULT 20
) RETURNS JSONB AS $$
DECLARE
  v_lead_id       UUID;
  v_lead          JSONB;
  v_conversations JSONB;
BEGIN
  -- Resolve lead_id from whichever identifier was supplied
  IF p_lead_id IS NOT NULL THEN
    v_lead_id := p_lead_id;
  ELSIF p_lead_email IS NOT NULL THEN
    SELECT lead_id INTO v_lead_id FROM leads WHERE lead_email = p_lead_email;
  ELSIF p_linkedin_profile_url IS NOT NULL THEN
    SELECT lead_id INTO v_lead_id FROM leads WHERE linkedin_profile_url = p_linkedin_profile_url;
  ELSIF p_phone_e164 IS NOT NULL THEN
    SELECT lead_id INTO v_lead_id FROM leads WHERE phone_e164 = p_phone_e164;
  END IF;

  IF v_lead_id IS NULL THEN
    RETURN jsonb_build_object(
      'lead',          NULL,
      'conversations', '[]'::jsonb,
      'error',         'lead_not_found'
    );
  END IF;

  SELECT to_jsonb(l.*) INTO v_lead FROM leads l WHERE l.lead_id = v_lead_id;

  SELECT jsonb_agg(c.*)
    INTO v_conversations
    FROM (
      SELECT *
      FROM   conversations
      WHERE  lead_id = v_lead_id
      ORDER  BY timestamp DESC
      LIMIT  p_max_events
    ) c;

  RETURN jsonb_build_object(
    'lead',          v_lead,
    'conversations', COALESCE(v_conversations, '[]'::jsonb)
  );
END;
$$ LANGUAGE plpgsql STABLE;


-- ============================================================
-- VERIFY — should return 4 rows and correct counts
-- ============================================================
SELECT
  (SELECT COUNT(*) FROM leads)                                    AS leads_total,
  (SELECT COUNT(*) FROM leads WHERE lead_id IS NOT NULL)          AS leads_with_id,
  (SELECT COUNT(*) FROM conversations WHERE lead_id IS NOT NULL)  AS convs_with_id,
  (SELECT COUNT(*) FROM follow_up_queue WHERE lead_id IS NOT NULL) AS queue_with_id,
  (SELECT COUNT(*) FROM follow_up_queue WHERE outcome IS NOT NULL) AS queue_with_outcome;
