-- MCO Unified Outreach Store — Supabase Setup
-- Run this entire script in the Supabase SQL Editor (supabase.com → your project → SQL Editor)

-- ============================================================
-- TABLE: leads
-- Canonical lead record. Primary key is email address.
-- For LinkedIn leads with no email yet, use placeholder:
--   urn_{linkedin_urn_slug}@linkedin.placeholder
-- Merge placeholder → real email when Clay resolves it.
-- ============================================================
CREATE TABLE IF NOT EXISTS leads (
  lead_email                TEXT PRIMARY KEY,
  full_name                 TEXT,
  company                   TEXT,
  linkedin_urn              TEXT,
  linkedin_profile_url      TEXT,
  phone_e164                TEXT,
  first_channel             TEXT CHECK (first_channel IN ('email','linkedin','voice','sms')),
  first_seen_at             TIMESTAMPTZ,
  last_activity_at          TIMESTAMPTZ,
  last_active_channel       TEXT CHECK (last_active_channel IN ('email','linkedin','voice','sms')),
  monday_item_id            TEXT,
  clay_enriched             BOOLEAN DEFAULT FALSE,
  overall_intent            TEXT DEFAULT 'unknown'
                              CHECK (overall_intent IN (
                                'unknown','no_action','not_interested',
                                'referral','already_have_contract','interested','booking'
                              )),
  overall_intent_updated_at TIMESTAMPTZ,
  aimfox_campaign           TEXT,
  email_sender_inbox        TEXT,
  notes                     TEXT,
  created_at                TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_leads_phone  ON leads(phone_e164);
CREATE INDEX IF NOT EXISTS idx_leads_intent ON leads(overall_intent);
CREATE INDEX IF NOT EXISTS idx_leads_last_activity ON leads(last_activity_at DESC);


-- ============================================================
-- TABLE: conversations
-- Every single interaction across all channels lives here.
-- event_id is a UUID v4 generated by the calling workflow.
-- Duplicate event_id writes are silently ignored (ON CONFLICT DO NOTHING).
-- ============================================================
CREATE TABLE IF NOT EXISTS conversations (
  event_id              UUID PRIMARY KEY,
  lead_email            TEXT NOT NULL REFERENCES leads(lead_email) ON UPDATE CASCADE,
  timestamp             TIMESTAMPTZ NOT NULL,
  channel               TEXT NOT NULL CHECK (channel IN ('email','linkedin','voice','sms')),
  direction             TEXT NOT NULL CHECK (direction IN ('inbound','outbound')),
  content               TEXT,
  content_type          TEXT CHECK (content_type IN ('message','transcript','summary')),
  sender_name           TEXT,
  intent                TEXT CHECK (intent IN (
                          'unknown','no_action','not_interested',
                          'referral','already_have_contract','interested','booking'
                        )),
  metadata_json         JSONB,
  workflow_execution_id TEXT,
  written_at            TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_conv_lead_time ON conversations(lead_email, timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_conv_channel   ON conversations(channel);
CREATE INDEX IF NOT EXISTS idx_conv_intent    ON conversations(intent);


-- ============================================================
-- TABLE: phone_map
-- Maps E.164 phone numbers to canonical lead_email.
-- Source: clay (enrichment), manual, or retell (self-reported).
-- ============================================================
CREATE TABLE IF NOT EXISTS phone_map (
  phone_e164  TEXT PRIMARY KEY,
  lead_email  TEXT REFERENCES leads(lead_email) ON UPDATE CASCADE,
  source      TEXT CHECK (source IN ('clay','manual','retell')),
  confidence  TEXT CHECK (confidence IN ('high','medium','low')),
  created_at  TIMESTAMPTZ DEFAULT NOW(),
  notes       TEXT
);

CREATE INDEX IF NOT EXISTS idx_phonemap_email ON phone_map(lead_email);


-- ============================================================
-- TABLE: follow_up_queue
-- Cross-channel follow-up triggers.
-- When a lead is interested on one channel, we queue follow-ups
-- on other channels here. The dispatcher workflow polls this
-- every 15 minutes and sends pending follow-ups.
-- ============================================================
CREATE TABLE IF NOT EXISTS follow_up_queue (
  queue_id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  lead_email        TEXT NOT NULL REFERENCES leads(lead_email) ON UPDATE CASCADE,
  trigger_channel   TEXT NOT NULL CHECK (trigger_channel IN ('email','linkedin','voice','sms')),
  target_channel    TEXT NOT NULL CHECK (target_channel IN ('email','linkedin','voice','sms')),
  trigger_event_id  UUID REFERENCES conversations(event_id),
  scheduled_for     TIMESTAMPTZ NOT NULL,
  status            TEXT NOT NULL DEFAULT 'pending'
                      CHECK (status IN ('pending','sent','skipped','failed')),
  follow_up_context TEXT,
  sent_at           TIMESTAMPTZ,
  created_at        TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_queue_status_time ON follow_up_queue(status, scheduled_for);
CREATE INDEX IF NOT EXISTS idx_queue_lead        ON follow_up_queue(lead_email);


-- ============================================================
-- ROW LEVEL SECURITY
-- Enabled on all tables. No policies = anon key is blocked.
-- The service_role key (used by n8n and Retool) bypasses RLS
-- entirely, so this has zero impact on functionality.
-- ============================================================
ALTER TABLE leads            ENABLE ROW LEVEL SECURITY;
ALTER TABLE conversations    ENABLE ROW LEVEL SECURITY;
ALTER TABLE phone_map        ENABLE ROW LEVEL SECURITY;
ALTER TABLE follow_up_queue  ENABLE ROW LEVEL SECURITY;


-- ============================================================
-- HELPER: intent_rank()
-- Used to enforce the promotion-only rule on overall_intent.
-- Call this in your n8n Code node or from a Postgres function.
-- ============================================================
CREATE OR REPLACE FUNCTION intent_rank(intent TEXT) RETURNS INT AS $$
BEGIN
  RETURN CASE intent
    WHEN 'unknown'                THEN 0
    WHEN 'no_action'              THEN 1
    WHEN 'not_interested'         THEN 2
    WHEN 'referral'               THEN 3
    WHEN 'already_have_contract'  THEN 4
    WHEN 'interested'             THEN 5
    WHEN 'booking'                THEN 6
    ELSE -1
  END;
END;
$$ LANGUAGE plpgsql IMMUTABLE;


-- ============================================================
-- HELPER: upsert_lead()
-- Atomic upsert that enforces the intent promotion hierarchy.
-- Call this from n8n via Supabase RPC node.
-- ============================================================
CREATE OR REPLACE FUNCTION upsert_lead(
  p_lead_email            TEXT,
  p_full_name             TEXT DEFAULT NULL,
  p_company               TEXT DEFAULT NULL,
  p_linkedin_urn          TEXT DEFAULT NULL,
  p_linkedin_profile_url  TEXT DEFAULT NULL,
  p_phone_e164            TEXT DEFAULT NULL,
  p_channel               TEXT DEFAULT NULL,
  p_monday_item_id        TEXT DEFAULT NULL,
  p_new_intent            TEXT DEFAULT NULL,
  p_aimfox_campaign       TEXT DEFAULT NULL,
  p_email_sender_inbox    TEXT DEFAULT NULL
) RETURNS TABLE(lead_created BOOLEAN, monday_item_id TEXT, overall_intent TEXT) AS $$
DECLARE
  v_created         BOOLEAN := FALSE;
  v_monday_item_id  TEXT;
  v_overall_intent  TEXT;
BEGIN
  INSERT INTO leads (
    lead_email, full_name, company, linkedin_urn, linkedin_profile_url,
    phone_e164, first_channel, first_seen_at, last_activity_at,
    last_active_channel, monday_item_id, overall_intent,
    overall_intent_updated_at, aimfox_campaign, email_sender_inbox, created_at
  ) VALUES (
    p_lead_email,
    COALESCE(p_full_name, ''),
    COALESCE(p_company, ''),
    p_linkedin_urn,
    p_linkedin_profile_url,
    p_phone_e164,
    p_channel,
    NOW(),
    NOW(),
    p_channel,
    p_monday_item_id,
    COALESCE(p_new_intent, 'unknown'),
    NOW(),
    p_aimfox_campaign,
    p_email_sender_inbox,
    NOW()
  )
  ON CONFLICT (lead_email) DO UPDATE SET
    full_name             = COALESCE(EXCLUDED.full_name,   leads.full_name),
    company               = COALESCE(EXCLUDED.company,     leads.company),
    linkedin_urn          = COALESCE(EXCLUDED.linkedin_urn, leads.linkedin_urn),
    phone_e164            = COALESCE(EXCLUDED.phone_e164,  leads.phone_e164),
    last_activity_at      = NOW(),
    last_active_channel   = EXCLUDED.last_active_channel,
    monday_item_id        = COALESCE(EXCLUDED.monday_item_id, leads.monday_item_id),
    aimfox_campaign       = COALESCE(EXCLUDED.aimfox_campaign, leads.aimfox_campaign),
    email_sender_inbox    = COALESCE(EXCLUDED.email_sender_inbox, leads.email_sender_inbox),
    overall_intent        = CASE
                              WHEN intent_rank(EXCLUDED.overall_intent) > intent_rank(leads.overall_intent)
                              THEN EXCLUDED.overall_intent
                              ELSE leads.overall_intent
                            END,
    overall_intent_updated_at = CASE
                              WHEN intent_rank(EXCLUDED.overall_intent) > intent_rank(leads.overall_intent)
                              THEN NOW()
                              ELSE leads.overall_intent_updated_at
                            END;

  SELECT leads.monday_item_id, leads.overall_intent
    INTO v_monday_item_id, v_overall_intent
    FROM leads WHERE leads.lead_email = p_lead_email;

  RETURN QUERY SELECT v_created, v_monday_item_id, v_overall_intent;
END;
$$ LANGUAGE plpgsql;


-- ============================================================
-- VERIFY: quick sanity check — should return 4 tables
-- ============================================================
SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public'
  AND table_name IN ('leads','conversations','phone_map','follow_up_queue')
ORDER BY table_name;
